### PR TITLE
Update crypt-city-of-the-deathless-one.xhtml

### PR DESCRIPTION
**Pull request by guppy-jpf**
"tendencies" -> "tentacles" ...
i have no reason for this change other than it seems to make more sense. maybe what happened is, in the process of ocr-ing the source, the word was misinterpreted, but it passed spellcheck and proofreading because it wasn't incorrect in any way other than semantically?

(btw, keep up the good work!)

### CODE REVIEW

**Comment by acabal** [comment]
Thanks! It is `tendencies` in print so it must be a printer's typo.

**Comment by guppy-jpf** [comment]
@acabal 
sorry for contacting you through this already-closed PR, but ...

i've found a couple other typos, but i can't figure out how to fix them,
because i can't seem to find them by searching the repo.  i'm not that 
familiar with the structure of epub, but my assumption that there would
be one file per story seems to be incorrect, as, in my recollection, there
are more stories in the book than there are files in `src/epub/text`.
in particular, the strings i'd like to correct aren't present in the source,
although they show up on my kindle.  does this repo not reflect the entire
contents of the book?

in any case, the two typos are:
1. in "the way of the gods" (i think), the string "steady beasts" should probably be "steady beats"
2. in another story (forgot which one, but there's a character named orelle in it i think), there's a string "it that right", which should probably be "is that right"

**Comment by acabal** [comment]
Hello, this ebook was recently updated to remove some stories that have been removed at Project Gutenberg. You are likely referring to those stories. Since they are no longer in this ebook, you wouldn't have found them in the repo.

**Comment by guppy-jpf** [comment]
thanks for the clarification.  thought i might have been crazy.
glad i have the previous "edition", errors notwithstanding ...
happy holidays and keep up the good work!

**Pull request merged**
